services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      SANIC_USE_ENV: "true"
      SANIC_PRODUCTION: "true"
      SANIC_HOST: "0.0.0.0"
      SANIC_GEMINI_API_KEY: ""
      SANUC_NEIS_API_KEY: ""
      SANIC_DB_URL: "postgresql+asyncpg://postgres_user:backendpasswd@postgres-backend:5432/backend_db"
      SANIC_VALKEY_URL: "valkey://valkey-backend:6379/"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - valkey


  postgres:
    image: postgres
    container_name: postgres-backend
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: backendpasswd
      POSTGRES_DB: backend_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432


  valkey:
    image: valkey/valkey:latest
    container_name: valkey-backend
    expose:
      - 6379
    depends_on:
      - postgres


volumes:
  pgdata: