services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      SANIC_USE_ENV: "true"
      SANIC_PRODUCTION: "true"
      SANIC_GEMINI_API_KEY: ""
      SANUC_NEIS_API_KEY: ""
      SANIC_DB_URL: "postgres://postgres_user:backendpasswd@postgres:5431/backend_db"
      SANIC_VALKEY_URL: "valkey://valkey:6379/"
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - valkey


  postgres:
    image: postgres
    container_name: postgres-backend
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: backendpasswd
      POSTGRES_DB: backend_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  valkey:
    image: valkey/valkey:latest
    container_name: valkey-backend
    ports:
      - "6379:6379"
    depends_on:
      - postgres


volumes:
  pgdata: